/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ph.edu.dlsu.EMI.myqueue.MyQueue;

/**
 *
 * @author inicca
 */
public class CodeExchangeSubmissionPanelForm extends javax.swing.JPanel {
    MyQueue temp = new MyQueue();
    CodeExchangeDataBase databaseProfiles;
    CodeExchangeRequestsDatabase databaseRequests;
    CodeExchangeSubmissionDatabase databaseSubmissions ;
    CodeExchangeSubmission submission;
    CodeExchangeSubmission tempSubmission;
    CodeExchangeCoderProfile profile;
    CodeExchangeUserProfile  userprofile;
    String requester;
    String n = System.lineSeparator();
    /**
     * Creates new form CodeExchangeProjectPanelForm
     * @param request
     */
    public CodeExchangeSubmissionPanelForm(CodeExchangeSubmission submission) throws IOException {
        initComponents();
        this.submission = submission;
        setLabels(submission);
        databaseSubmissions = new CodeExchangeSubmissionDatabase();
         databaseRequests = new CodeExchangeRequestsDatabase();
         databaseProfiles = new CodeExchangeDataBase();
         userprofile=databaseProfiles.getProfileUser(submission.getRequester());
    }

    

  
        
    public void setLabels(CodeExchangeSubmission submission){
        submitterLabel.setText(submission.getSubmitter());
        featuresLabel.setText(submission.getFeatures());
        addfeatureslabel.setText(submission.getAddFeatures());
        screenshotLabel.setText(submission.getScreenshot());
        languageLabel.setText(submission.getLanguage());
        codeLabel.setText(submission.getCode()+"");
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        languageLabel = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        submitterLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        featuresLabel = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        screenshotLabel = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        codeLabel = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        addfeatureslabel = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();

        label1.setText("label1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Screenshots:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Features Done: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Language Used:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Actual Code:");

        languageLabel.setText("label2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Submitted by: ");

        submitterLabel.setText("jLabel7");

        featuresLabel.setEditable(false);
        featuresLabel.setColumns(20);
        featuresLabel.setRows(5);
        jScrollPane1.setViewportView(featuresLabel);

        screenshotLabel.setEditable(false);
        screenshotLabel.setColumns(20);
        screenshotLabel.setRows(5);
        jScrollPane2.setViewportView(screenshotLabel);

        codeLabel.setEditable(false);
        codeLabel.setColumns(20);
        codeLabel.setRows(5);
        jScrollPane3.setViewportView(codeLabel);

        addfeatureslabel.setEditable(false);
        addfeatureslabel.setColumns(20);
        addfeatureslabel.setRows(5);
        jScrollPane4.setViewportView(addfeatureslabel);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Additional Features:");

        acceptButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        acceptButton.setText("Accept this");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                                .addGap(63, 63, 63))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(71, 71, 71)
                        .addComponent(languageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(83, 83, 83)
                        .addComponent(submitterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptButton)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitterLabel)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(acceptButton)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(languageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure?","Confirm",JOptionPane.YES_NO_OPTION);
        if(choice == 0){
            CodeExchangeCoderProfile tempProfile = databaseProfiles.getProfileCoder(submission.getSubmitter());
            tempProfile.setEarnings(tempProfile.getEarnings()+ databaseRequests.findByTitle(submission.getTitle()).getPayment());
            
            try {
                removefromText();
            } catch (IOException ex) {
                Logger.getLogger(CodeExchangeSubmissionPanelForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(submission.getTitle());
            try {
                databaseRequests.removeByTitle(submission.getTitle());
                databaseProfiles.saveDatabase();
                System.out.println("Removed in the database succesfully");
            } catch (IOException ex) {
                Logger.getLogger(CodeExchangeSubmissionPanelForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(null, "Accepted this work!");
            
                
            
}else{
            System.out.println("cancelled by the user ");
        }
        
        
    }//GEN-LAST:event_acceptButtonActionPerformed
            
    public void removefromText() throws IOException{
        PrintWriter print = null;
        String path = System.getProperty("user.dir") + "\\src\\project\\projectlist\\projectlist.txt";
        FileWriter writer;
        try {
            writer = new FileWriter(path, false);
            print = new PrintWriter(writer);
            print.println("");
            print.close();
        } catch (IOException ex) {
            Logger.getLogger(RegistrationUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=databaseSubmissions.submission.size()-1;i>0;i--){
            databaseRequests.removeByTitle(submission.getTitle());
//            tempSubmission=databaseSubmissions.submission.deQueue();
//            System.out.println(userprofile.getName()+tempSubmission.getRequester());
//            if(!tempSubmission.getRequester().equals(userprofile.getName())&&!tempSubmission.getTitle().equals(submission.getTitle())){
//            writer = new FileWriter(path, true);
//            print = new PrintWriter(writer);
//            print.println(tempSubmission.getSubmitter()+n+tempSubmission.getTitle()+n+tempSubmission.getRequester()+n+tempSubmission.getLanguage()+n+"end language"+ n +tempSubmission.getFeatures()+n+"end features" + n +tempSubmission.getScreenshot()+n+"end shots" + n +tempSubmission.getAddFeatures()+n+"end added features"+ n +tempSubmission.getCode()+n+"end code"+ n + "end");
//            temp.enQueue(tempSubmission);
//            }
//            while(!temp.isEmpty()){
//                databaseSubmissions.submission.enQueue((CodeExchangeSubmission) temp.deQueue());
//            }
            
            
            
            
        }
        print.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JTextArea addfeatureslabel;
    private javax.swing.JTextArea codeLabel;
    private javax.swing.JTextArea featuresLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label1;
    private java.awt.Label languageLabel;
    private javax.swing.JTextArea screenshotLabel;
    private javax.swing.JLabel submitterLabel;
    // End of variables declaration//GEN-END:variables
}
